#!/bin/sh
#
# File:    mkauctabrow.sh
# Author:  Alex Stivala
# Created: March 2009
#
# mkauctabrow.sh - make a row in the LaTeX table of AUC values for
#                  QP tableau search and other methods on large data set
#            
#
# Usage: mkauctabrow statsfiename
#
# statsfilename is the .stats file generated by the rocauc.r R program
# from the .slrtab file generated fby the 
# rocrfischer.py script (all this is done from Makefile)
#
# Output is to stdout
#
# $Id: mkauctabrow.sh 3612 2010-05-05 01:32:37Z alexs $
#

if [ $# -ne 1 ]; then
    echo "Usage: $0 statsfilename" 2>&1
    exit 1
fi

statsfile=$1


#auc=`fgrep 'RROC          AUC' ${statsfile} | cut -d= -f2`
auc=`fgrep 'Hanley-McNeil AUC' ${statsfile} | cut -d= -f2`
stderror=`fgrep 'std. error' ${statsfile} | cut -d= -f2`
interval95=`fgrep '95% CI' ${statsfile} | cut -d= -f2`
low95=`echo "${interval95}" | cut -d, -f1`
high95=`echo "${interval95}" | cut -d, -f2`

printf "%6.3f & %5.3f & %6.3f & %6.3f " $auc $stderror $low95 $high95
echo \\\\

