#!/bin/sh
#
# File:    mkfischer3dtabrow.sh
# Author:  Alex Stivala
# Created: October 2008
#
# mkfischer3dtabrow.sh - make a row in the LaTeX table of results for MSVNS and
#                  QP tableau search on Fischer and Nh3D data sets
#            
#
# Usage: mkfischer3dtabrow statsfiename
#
# statsfilename is the .stats file generated by the rocauc.r R program
# from the .slrtab file generated from MSVNS or tsrchd output by the 
# rocrfischer.py script (all this is done from Makefile)
#
# Output is to stdout
#
# $Id: mkfischer3dtabrow.sh 3686 2010-05-17 07:31:00Z alexs $
#

if [ $# -ne 1 ]; then
    echo "Usage: $0 statsfilename" 2>&1
    exit 1
fi

statsfile=$1

auc=`fgrep 'Hanley-McNeil AUC' ${statsfile} | cut -d= -f2`
stderror=`fgrep 'std. error' ${statsfile} | cut -d= -f2`
interval95=`fgrep '95% CI' ${statsfile} | cut -d= -f2`
low95=`echo "${interval95}" | cut -d, -f1`
high95=`echo "${interval95}" | cut -d, -f2`

printf "%6.3f & %5.3f & %6.3f & %6.3f " $auc $stderror $low95 $high95
echo '\\'

