#!/bin/sh
#
# File:    mkfischer3dtab.sh
# Author:  Alex Stivala
# Created: October 2008
#
# mkfischer3dtab.sh - make LaTeX table of results for MSVNS and
#                     QP tableau search on Fischer and Nh3D data sets
#            
# Uses the mkfischer3dtabrow.sh script to make row from .stats file
# previously generated by various scripts (in Makefile)
#
# Usage: mkfischer3dtab.sh dataset level
#
# dataset is fischer or nh3d
# level is class or fold (fischer) or arch or class (nh3d)
# Output is to stdout
#
# Uses options specific to GNU sort
#
# $Id: mkfischer3dtab.sh 1961 2008-10-07 06:08:06Z astivala $
#

if [ $# -ne 2 ]; then
    echo "Usage: $0 dataset level" 2>&1
    exit 1
fi
dataset=$1
level=$2
for statsdir in results/${dataset} results/${dataset}/norm? maxcmo_results/${dataset} maxcmo_results/${dataset}/norm?
do
    lastpart=`basename ${statsdir}`
    if [ `expr substr ${lastpart} 1 4` = "norm" ]; then
        normtype=${lastpart}
    else
        normtype="None"
    fi
    resdir=`echo ${statsdir} | cut -d/ -f1`
    if [ ${resdir} = "results" ]; then
        method="QP tableau search"
    elif [ ${resdir} = "maxcmo_results" ]; then
        method="MSVNS3"
    else
        echo "unknown directory ${resdir}" 2>&1
    fi
    for statsfile in ${statsdir}/${level}.stats
    do
        level=`basename ${statsfile} .stats`
        printf '%-20s & %-5s &' "${method}"  "${normtype}"
        mkfischer3dtabrow.sh ${statsfile}
    done
done | sort -t'&'  -k1,1 -k2,2 

