#!/bin/sh
#
# File:    mkquery200tab.sh
# Author:  Alex Stivala
# Created: March 2009
#
# mkquery200tab.sh - make LaTeX table of AUC values for 
#               QP tableau search and other methods on query200 data set
#            
# Uses the mkauctabrow.sh script to make row from .stats file
# previously generated by various scripts (in Makefile)
#
# Usage: mkquery200tab.sh
#
# dataset is fischer or nh3d
# level is class or fold (fischer) or arch or class (nh3d)
# Output is to stdout
#
# Uses options specific to GNU sort
#
# $Id: mkquery200tab.sh 2153 2009-03-28 05:20:23Z astivala $
#

if [ $# -ne 0 ]; then
    echo "Usage: $0" 2>&1
    exit 1
fi

# cat <<EOF
# \begin{tabular}{llrrrr} 
# \hline
#  & & & & \multicolumn{2}{c}{95\% confidence interval} \\\\
# Method & Normalization & AUC & std. error & lower & upper \\\\
# \hline
# EOF

# commented out above since Hanley-McNeil R script broken (see mkauctabrow.sh)
cat <<EOF
\begin{tabular}{llr} 
\hline
Method & Normalization & AUC  \\\\
\hline
EOF


for statsfile in results/query200/*.stats results/query200/norm?/*.stats other_results/sheba/query200-pdbstyle-sel-gs-bib-95-1.73/*.stats other_results/vast/vast_query200_res/*.stats other_results/TableauSearch/query200/*.stats other_results/TableauSearch/query200/norm?/*.stats other_results/tops/query200/*.stats
do
    lastdir=`dirname ${statsfile}`
    lastpart=`basename ${lastdir}`
    if [ `expr substr ${lastpart} 1 4` = "norm" ]; then
        normtype=${lastpart}
    else
        normtype="None"
    fi
    resdir=`echo ${statsfile} | cut -d/ -f1`
    if [ ${resdir} = "results" ]; then
        method="QP tableau search"
    else
        method=`echo ${statsfile} | cut -d/ -f2`
        if [ "${method}" != "TableauSearch" ]; then
            method=`echo "${method}" | tr a-z A-Z`
        fi
    fi
    printf '%-20s & %-5s &' "${method}"  "${normtype}"
    mkauctabrow.sh ${statsfile}
done | sort -t'&'  -k3,3nr

cat <<EOF
\hline
\end{tabular}
EOF
