# autogenerated by /home/alexs/phd/ptgraph/buildversion.sh
# Mon Nov 23 16:31:03 EST 2009
def get_version():
    """
    Return version string containing global version number and 'build' date
    """
    return "Revision 2978, Mon Nov 23 16:31:03 EST 2009"
