# autogenerated by ./buildversion.sh
# Tue Jun 29 17:03:49 EST 2010
def get_version():
    """
    Return version string containing global version number and 'build' date
    """
    return "Revision 3839M, Tue Jun 29 17:03:49 EST 2010"
