#!/usr/bin/env python
###############################################################################
#
# qptabmatch_allpairs.py - run the QP tableau matching pairwise on all
#                          tableaux in a directory
#
# File:    qptabmatch_allpairs.py
# Author:  Alex Stivala
# Created: September 2008
#
#
# Run QP tableau match on all pairs of tableaux in a directory such
# as that created by build_skolnick_db.sh. Each file in the directory
# has a .tableaudistmatrix suffix and contains the header line with
# identifeir and dimension, then tabelau and SSE distance matrix
# (both lower triangle fortran format
# for tsrchrd_sparse etc.)
#
# This does not do duplicate comparisons (i.e. runs on a,b exactly once,
# does not also run on b,a) so for n .tableaudistmatrix files gives
# n(n-1)/2 scores.
# 
#
# Usage:
#     qptabmatch_allpairs.py db_directory
#
# db_directory is the directory containing .tableaudistmatrix files,
# as built with build_skolnick_db.sh for example.
#
# Output is to stdout, tab-delimited in the format
# 
#   pdbid1 pdbid2 score
#
# e.g.
#
#  1BAW     1KDI  -50.9997
#
# Environment variables:
#
#   PATH must contain the location of tsrchd_sparse.
#   The dssp program must also be in the PATH.
#
#
# $Id: qptabmatch_allpairs.py 1884 2008-09-11 07:59:29Z astivala $
# 
###############################################################################

import sys,os,glob
from time import strftime,localtime


def usage(progname):
    """
    Print usage message and exit
    """
    sys.stderr.write("Usage: " + progname + " <db_directory>\n")
    sys.exit(1)

    
def main():
    """
    main for qptabmatch_allpairs.py
    """
    if len(sys.argv) != 2:
        usage(os.path.basename(sys.argv[0]))

    db_directory = sys.argv[1]
    
    sys.stdout.write('# Generated by: \n')
    sys.stdout.write('# ' + ' '.join(sys.argv))
    sys.stdout.write('\n')
    timestamp = strftime("%d%b%Y %H:%M:%S", localtime())
    sys.stdout.write('# on ' + timestamp + '\n')
    sys.stdout.write('#\n')    

    input_list = glob.glob(os.path.join(db_directory, '*.tableaudistmatrix'))
    i = 0
    while i < len(input_list):
        j = i + 1
        while j < len(input_list):
            file1 = input_list[i]
            file2 = input_list[j]
            qid = open(file1).readline()[:8].lstrip().rstrip()
            (tsrchd_in, tsrchd_out) = os.popen2(['tsrchd_sparse'])
            tsrchd_in.write(file2 + '\n')   # name of db file
            tsrchd_in.write('T T F\n') # LTYPE LORDER LSOLN
            tsrchd_in.write(open(file1).read()) # tableau dn distmatrix of file1
            tsrchd_in.close()
            for line in  tsrchd_out:
                if line[0] == '#':
                    continue
                pdbid = line[:8].lstrip().rstrip()
                score = float(line[7:])
                break
            tsrchd_out.close()
            sys.stdout.write('%s\t%s\t%.4f\n' % (qid, pdbid, score))
            j += 1
        i += 1

if __name__ == "__main__":
    main()

