#!/bin/sh
###############################################################################
#
# tsevalfischer_all.sh - run tsevalfischer.py on all output in a directory
#
# File:    tsevalfischer_all.sh
# Author:  Alex Stivala
# Created: September 2008
#
# Run the tsevalfischer.py script on all .out files in the supplied
# directory, creating correpsonding .rtab files in that directory
# WARNING: overwrites the .rtab files if they exist
#
# query id is dervied from filename e.g. 8i1b.out is for 8i1b query,
# output is produced in this form from qptabmatch_allall.py script
# from input generated by build_fischer_db.sh script
#
#
# Also print average AUC to stdout
#
# Usage:
#     tsevalfischer_all.sh [-rc] outdir
#
#     -c   evaluate on class not fold level (produces .class.rtab not
#          .fold.rtab files)
#     -n   negate scores so that most -ve is best
#     -x   exclude folds that don't appear to be inlucded in Pelta et al 2008
#          Figure 5.
#
#    outdir is the directory containing the .out files and to which the
#    .rtab files are to be written.
#
# Environment variables:
#
#   PATH must contain the location of the Python scripts, ie where this
#   script itself is, and tsevalfischer.py
#
#   PYTHONPATH must contain the directory containing the tsevalutils.py 
#   and other Python modules used by the Python scripts.
#
# $Id: tsevalfischer_all.sh 2079 2009-03-03 07:43:11Z astivala $
# 
###############################################################################

# OBSOLETE - use rocrfischer.py and rocauc.r now

use_class=0
negate=0
use_skip=0

# skip the following folds that for some reason arenot included in 
# Pelta et al 2008 assessment (see Figure 5):
# cytochrome, mixed, small, copredoxin, lectin-like, ob-fold, trefoil,
# propellor, ub-fold, cystatin, sh2
# (27 folds in Fischer Table II but only 16 in Pelta Figure 5).
SKIP_IDS="1c2r_a 2mta_c 2hhm_a 1hip 1isu_a 1aaj 2afn_a 2aza_a 1sac_a 1lts_d 1tie 8i1b 2sim 1fxi_a 1cew 1stf_i 2pna"

while getopts 'ncx' opt
do
    case $opt in
    n) negate=1
    ;;
    c) use_class=1
    ;;
    x) use_skip=1
    ;;
    ?)
    echo "Usage: $0 [-nc] outdir" >&2
    exit 1
    ;;
    esac
done
shift `expr $OPTIND - 1`

if [ $# -ne 1 ]; then
    echo "Usage: $0 [-rc] outdir" >&2
    exit 1
fi
    
outdir=$1

if [ $use_class -eq 1 ]; then
    if [ $use_skip -eq 1 ]; then
        echo "$0: -x ignored as not applicable with -c" >&2
        use_skip=0
    fi
    suffix="class.rtab"
    pyopts="-c"
else
    suffix="fold.rtab"
    pyopts=""
fi

if [ $negate -eq 1 ]; then
    pyopts="${pyopts} -n"
fi

for resultfile in ${outdir}/*.out
do
    queryid=`basename ${resultfile} .out`
    if [ $use_skip -eq 1 ]; then
        for i in $SKIP_IDS
        do
            if [ $i = `echo $queryid | tr '[A-Z]' '[a-z]'` ]; then
#                echo xx $queryid
                continue 2
            fi
        done
    fi
    tsevalfischer.py ${pyopts} ${queryid} ${resultfile} > ${outdir}/${queryid}.${suffix}
done

grep 'AUC' ${outdir}/*.${suffix} | awk '{sum += $4}; END {printf("for %d results, average AUC is %4.2f\n", NR, sum/NR)}'


