#!/bin/sh
###############################################################################
#
# tsevalnh3d_all.sh - run tsevalnh3d.py on all output in a directory
#
# File:    tsevalnh3d_all.sh
# Author:  Alex Stivala
# Created: September 2008
#
# Run the tsevalnh3d.py script on all .out files in the supplied
# directory, creating correpsonding .rtab files in that directory
# WARNING: overwrites the .rtab files if they exist
#
# query id is dervied from filename e.g. 1.10.1290.out is for 1.10.1290 query,
# output is produced in this form from qptabmatch_allall.py script
# from input generated by build_nh3d_db.sh script
#
#
# Also print average AUC to stdout for each CATH architecture
#
# Usage:
#     tsevalnh3d_all.sh [-n] outdir
#
#     -n   negate scores (so that most -ve is best rather than highest)
#
# Environment variables:
#
#   PATH must contain the location of the Python scripts, ie where this
#   script itself is, and tsevalnh3d.py
#
#   PYTHONPATH must contain the directory containing the tsevalutils.py 
#   and other Python modules used by the Python scripts.
#
# $Id: tsevalnh3d_all.sh 2079 2009-03-03 07:43:11Z astivala $
# 
###############################################################################

# OBSOLETE - use rocrnh3d.py and rocauc.r now

negate=0

while getopts 'n' opt
do
    case $opt in
    n) negate=1
    ;;
    ?)
    echo "Usage: $0 [-rc] outdir" >&2
    exit 1
    ;;
    esac
done
shift `expr $OPTIND - 1`

if [ $# -ne 1 ]; then
    echo "Usage: $0 [-r] outdir" >&2
    exit 1
fi
    
outdir=$1

pyopts=""
if [ $negate -eq 1 ]; then
    pyopts="${pyopts} -n"
fi

suffix='rtab'

for resultfile in ${outdir}/*.out
do
    queryid=`basename ${resultfile} .out`
    tsevalnh3d.py ${pyopts}  ${queryid} ${resultfile} > ${outdir}/${queryid}.${suffix}
done

# list of different CATH architectures 
# obtained by
# ls -1 results/nh3d/*.out |cut -d/ -f3 | cut -d. -f1,2|sort | uniq 
ARCH_LIST="1.10 1.20 2.10 2.170 2.30 2.40 2.60 2.70 3.10 3.20 3.30 3.40 3.60 3.90 4.10"

for arch in $ARCH_LIST
do
    grep 'AUC' ${outdir}/${arch}.*.${suffix} | awk "{sum += \$4}; END {printf(\"for %d results in CATH ${arch}, average AUC is %4.2f\n\", NR, sum/NR)}"
done

