#!/bin/bash
###############################################################################
#
# update_query_list_for_new_astral_version.sh.sh - 
#           update list of queries generated by genquerylist.sh for new ASTRAL
#
# File:    update_query_list_for_new_astral_version.sh.shb
# Author:  Alex Stivala
# Created: Februrary 2010
#
#
# Given a list of domain sids generated by genquerylist.sh, find those
# not in the supplied tableaux database file (due to it being a later
# ASTRAL SCOP version than that on which the query list was generated),
# generate a new list with domains that are not in the new version replaced
# with ones in the same superfamily that are in the new version.
#
# Used to update the query200 list generated with ASTRAL SCOP 1.73 
# to ASTRAL SCOP 1.75.
#
#
# Usage:
#     update_query_list_for_new_astral_version.sh.sh tableauxdb < query.list
#
# Environment variables:
#
#   PATH must contain the location of the Python scripts, ie where this
#   script itself is and the ptgraph/ directory with pytableaucreate.py etc.,
#   and the location of tsrchd_sparse.
#   The dssp program must also be in the PATH.
#
#   PYTHONPATH must contain the directory containing the
#    Python modules used by the Python scripts.
#
# $Id: update_query_list_for_new_astral_version.sh 3340 2010-02-14 23:08:09Z alexs $
# 
###############################################################################


if [ $# -ne 1 ]; then
    echo "usage: $0 tableauxdbfile < querylist" >&2
    exit 1
fi
tableauxdbfile=$1

while read sid
do
  grep $sid $tableauxdbfile >/dev/null 2>/dev/null
  if [ $? -ne 0 ]; then
      echo $sid  | scopdominfo.py | grep '^d' | cut  -f2 | cut -d'(' -f2 | \
          cut -d')' -f1 | getdomainsinsf.py
  else
      echo $sid
  fi
done

